apiVersion: v1
kind: Service
metadata:
  name: kit-service
  labels:
    app: kit
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    nodePort: 31100
  selector:
    app: kit